apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
spec:
  replicas: 200
  template:
    spec:
      containers:
        - name: stress
          resources:
            requests:
              cpu: 500m
              memory: 320Mi
          livenessProbe:
            exec:
              command:
              - stat
              - /stress-io/pod-running
            periodSeconds: 5
            timeoutSeconds: 3
          startupProbe:
            exec:
              command:
              - stat
              - /stress-io/pod-running
            failureThreshold: 7
            periodSeconds: 10
            timeoutSeconds: 3
